# -*- coding: utf-8 -*-
#
# Copyright (C) 2010-2016 PPMessage.
# Guijin Ding, dingguijin@gmail.com
# All rights are reserved
#

from ppmessage.core.constant import API_LEVEL
from ppmessage.core.constant import TASK_STATUS
from ppmessage.core.constant import MESSAGE_STATUS
from ppmessage.core.constant import MESSAGE_SUBTYPE
from ppmessage.core.constant import CONVERSATION_STATUS
from ppmessage.core.constant import SERVICE_USER_STATUS

from ppmessage.core.redis import row_to_redis_hash
from ppmessage.core.redis import redis_hash_to_dict
from ppmessage.core.imageconverter import ImageConverter

from .dbinstance import BaseModel
from .commonmixin import CommonMixin
from .dbinstance import getDBSessionClass

from sqlalchemy import Float
from sqlalchemy import Column
from sqlalchemy import String
from sqlalchemy import Integer
from sqlalchemy import Boolean
from sqlalchemy import DateTime
from sqlalchemy import LargeBinary

from sqlalchemy import Index

import os
import time
import uuid
import json
import hashlib
import logging
import datetime
import traceback

class DeviceUser(CommonMixin, BaseModel):
    __tablename__ = "device_users"

    user_name = Column("user_name", String(32))
    user_password = Column("user_password", String(256))
    user_email = Column("user_email", String(64))
    user_status = Column("user_status", String(64))
    user_firstname = Column("user_firstname", String(64))
    user_lastname = Column("user_lastname", String(64))
    user_fullname = Column("user_fullname", String(64))
    user_icon = Column("user_icon", String(512))
    user_mobile = Column("user_mobile", String(32))
    user_qq = Column("user_qq", String(64))
    user_wechat = Column("user_wechat", String(64))
    user_signature = Column("user_signature", String(128))
    
    ppkefu_browser_device_uuid = Column("ppkefu_browser_device_uuid", String(64))
    ppcom_browser_device_uuid = Column("ppcom_browser_device_uuid", String(64))
    
    # zh_cn/en_us/zh_tw
    user_language = Column("user_language", String(32))
        
    
    # ppcom portal user
    is_anonymous_user = Column("is_anonymous_user", Boolean)
    is_service_user = Column("is_service_user", Boolean)
    is_owner_user = Column("is_owner_user", Boolean)
    is_removed_user = Column("is_removed_user", Boolean, default=True)
    
    # ppcom trace id with web cookie
    ppcom_trace_uuid = Column("ppcom_trace_uuid", String(64))

    # lastest_send_message_time for idle algorithm
    latest_send_message_time = Column("latest_send_message_time", DateTime)

    geolite_latitude = Column("geolite_latitude", Float)
    geolite_longitude = Column("geolite_longitude", Float)

    # which is uuid of other/third party system
    ent_user_uuid = Column("ent_user_uuid", String(64))
    ent_user_createtime = Column("ent_user_createtime", DateTime)

    company_uuid = Column("company_uuid", String(64))
    
    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        return
        
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)

        _key = self.__tablename__ + ".is_service_user." + str(self.is_service_user)
        _redis.sadd(_key, self.uuid)

        if self.is_service_user == False and self.ent_user_uuid:
            _key = self.__tablename__ + ".ent_user_uuid." + self.ent_user_uuid
            _redis.set(_key, self.uuid)
        
        if self.is_service_user == True and not self.is_removed_user:
            _key = self.__tablename__ + ".user_email." + self.user_email
            _redis.set(_key, self.uuid)

        if self.ppcom_trace_uuid:
            _key = DeviceUser.__tablename__ + ".ppcom_trace_uuid." + self.ppcom_trace_uuid
            _redis.set(_key, self.uuid)
        
        return

    def delete_redis_keys(self, _redis):
        CommonMixin.delete_redis_keys(self, _redis)
        return    

    def update_redis_keys(self, _redis):
        CommonMixin.update_redis_keys(self, _redis)
        return
    
class DeviceInfo(CommonMixin, BaseModel):
    __tablename__ = "device_infos"

    # after allocation
    user_uuid = Column("user_uuid", String(64))
    
    # generated by terminal
    terminal_uuid = Column("terminal_uuid", String(64))

    # after update
    device_fullname = Column("device_fullname", String(256))
    # ios/android/windowsphone/windows/macosx upper letter
    device_phonenumber = Column("device_phonenumber", String(32))

    device_ostype = Column("device_ostype", String(32))
    device_osversion = Column("device_osversion", String(32))

    device_android_apilevel = Column("device_android_apilevel", String(32))

    device_android_gcmtoken = Column("device_android_gcmtoken", String(64))

    device_android_jpush_registrationid = Column("device_android_jpush_registrationid", String(64))
    
    device_ios_model = Column("device_ios_model", String(32))
    device_ios_token = Column("device_ios_token", String(64))

    # online ppkefu
    api_session_uuid = Column("api_session_uuid", String(64))

    # online for ppcom and ppkefu
    device_is_online = Column("device_is_online", Boolean)

    # accelerate the online devices of portal users
    is_ppcom_device = Column("is_ppcom_device", Boolean)

    # is_development
    is_development = Column("is_development", Boolean)
    
    __table_args__ = ()

    def __init__(self, *args, **kwargs):
        super(DeviceInfo, self).__init__(*args, **kwargs)
        return
        
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        _key = self.__tablename__ + ".terminal_uuid." + self.terminal_uuid
        _redis.set(_key, self.uuid)

        _key_0 = self.__tablename__ + \
                 ".is_ppcom_device." + str(self.is_ppcom_device) + \
                 ".device_is_online." + str(self.device_is_online)
        _key_1 = self.__tablename__ + \
                 ".is_ppcom_device." + str(self.is_ppcom_device) + \
                 ".device_is_online." + str(not self.device_is_online)
        
        _updatetime = time.mktime(self.updatetime.timetuple())*1000*1000 + self.updatetime.microsecond
        _v = json.dumps([self.user_uuid, self.uuid])
        _redis.zadd(_key_0, _v, _updatetime)
        _redis.zrem(_key_1, _v)
        return

    def update_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.update_redis_keys(self, _redis, *args, **kwargs)
        _obj = redis_hash_to_dict(_redis, DeviceInfo, self.uuid)
        if _obj == None:
            return

        _key_0 = self.__tablename__ + \
                 ".is_ppcom_device." + str(_obj["is_ppcom_device"]) + \
                 ".device_is_online." + str(_obj["device_is_online"])
        _key_1 = self.__tablename__ + \
                 ".is_ppcom_device." + str(_obj["is_ppcom_device"]) + \
                 ".device_is_online." + str(not _obj["device_is_online"])
        
        _updatetime = time.mktime(self.updatetime.timetuple())*1000*1000 + self.updatetime.microsecond
        _v = json.dumps([_obj["user_uuid"], self.uuid])
        _redis.zadd(_key_0, _v, _updatetime)
        _redis.zrem(_key_1, _v)
        return
    
    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, DeviceInfo, self.uuid)
        if _obj == None:
            return
        _key = self.__tablename__ + ".terminal_uuid." + _obj["terminal_uuid"]
        _redis.delete(_key)

        _key_0 = self.__tablename__ + \
                 ".is_ppcom_device." + str(_obj["is_ppcom_device"]) + \
                 ".device_is_online." + str(_obj["device_is_online"])
        _v = json.dumps([_obj["user_uuid"], self.uuid])
        _redis.zrem(_key_0, _v)
        
        CommonMixin.delete_redis_keys(self, _redis)
        return
        
class MessagePushTask(CommonMixin, BaseModel):

    __tablename__ = "message_push_tasks"
    
    conversation_uuid = Column("conversation_uuid", String(64))
    # P2S/S2P/S2S since conversationinfo no S2P
    conversation_type = Column("conversation_type", String(8))
    
    # message from
    from_uuid = Column("from_uuid", String(64))
    # admin_user/device_user/app_group
    from_type = Column("from_type", String(32))

    from_device_uuid = Column("from_device_uuid", String(64))
    to_device_uuid = Column("to_device_uuid", String(64))

    # message to
    to_uuid = Column("to_uuid", String(64))
    # app/org_group/device_user
    to_type = Column("to_type", String(32))
        
    # type NOTIFICATION/APP..., subtype text/card/image/audio/video
    message_type = Column("message_type", String(32))
    message_subtype = Column("message_subtype", String(32))

    # message body and title could be search
    # if text message body less than 128 bytes, the subtype is text
    # else the subtype is txt
    # store it in body otherwise body is a file uuid
    body = Column("body", String(256))
    title = Column("title", String(256))

    # message dump generated after sending to push server
    message_body = Column("message_body", String(512))

    # message push procedure
    task_status = Column("task_status", String(32))

    is_development = Column("is_development", Boolean)
    
    __table_args__ = (
        Index(
            "_idx_message_pushtask",
            "task_status",
        ),
    )

    def __init__(self, *args, **kwargs):
        super(MessagePushTask, self).__init__(*args, **kwargs)
        return
        
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
            
        if self.conversation_uuid != None:
            _key = self.__tablename__ + ".conversation_uuid." + self.conversation_uuid
            _createtime = time.mktime(self.createtime.timetuple())*1000*1000 + self.createtime.microsecond
            _redis.zadd(_key, self.uuid, _createtime)

        # by hour
        _key = self.__tablename__ + \
               ".day." + self.createtime.strftime("%Y-%m-%d") + \
               ".hour." + str(self.createtime.hour)
        _redis.incr(_key)

        # by day
        _key = self.__tablename__ + \
               ".day." + self.createtime.strftime("%Y-%m-%d")
        _redis.incr(_key)

        # all messages
        _key = self.__tablename__
        _redis.incr(_key)

        return
    
    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, MessagePushTask, self.uuid)
        if _obj == None:
            return

        if _obj.get("conversation_uuid") != None:
            _key = self.__tablename__ + ".conversation_uuid." + _obj["conversation_uuid"]
            _redis.zrem(_key, self.uuid)

        CommonMixin.delete_redis_keys(self, _redis)
        return
    
class MessagePush(CommonMixin, BaseModel):
    __tablename__ = "message_pushs"
    task_uuid = Column("task_uuid", String(64))
    user_uuid = Column("user_uuid", String(64))
    device_uuid = Column("device_uuid", String(64))
    status = Column("status", String(32))

    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(MessagePush, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        # ACKED PUSH NOT CACHED ANY LONGER
        if self.status == MESSAGE_STATUS.ACKED:
            return
        if self.task_uuid == None or self.user_uuid == None:
            return
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        _key = self.__tablename__ + ".user_uuid." + self.user_uuid
        _updatetime = time.mktime(self.updatetime.timetuple())*1000*1000 + self.updatetime.microsecond
        _redis.zadd(_key, self.uuid, _updatetime)
        return

    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, MessagePush, self.uuid)
        if _obj == None or _obj["task_uuid"] == None or _obj["user_uuid"] == None:
            return
        _key = self.__tablename__ + ".user_uuid." + _obj["user_uuid"]
        _redis.zrem(_key, self.uuid)
        CommonMixin.delete_redis_keys(self, _redis)
        return

class FileInfo(CommonMixin, BaseModel):
    __tablename__ = "file_infos"

    # the user is the owner
    user_uuid = Column("user_uuid", String(64))

    # application/x-yv-icon
    # application/x-yv-material-image
    # application/x-yv-material-image-thumbnail
    # application/x-yv-material-audio
    # application/x-yv-material-video
    # application/x-yv-material-document ? word/excel/ppt/pdf/etc.
    # application/x-yv-material-archive ? zip/rar/tar/gz/7z
    # application/x-yv-material-card ~ html

    material_type = Column("material_type", String(64))
    
    # original name if provided
    file_name = Column("file_name", String(128))
    file_size = Column("file_size", Integer)
    file_hash = Column("file_hash", String(64))
    file_mime = Column("file_mime", String(128))

    # absolute path
    file_path = Column("file_path", String(256))

    # the file is only a link which referencing other file
    file_ref = Column("file_ref", String(64))

    thumbnail_uuid = Column("thumbnail_uuid", String(64))

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        _key = self.__tablename__ + ".file_hash." + self.file_hash
        _redis.set(_key, self.uuid)
        return

    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, FileInfo, self.uuid)
        if _obj == None:
            return
        _key = self.__tablename__ + ".file_hash." + _obj["file_hash"]
        _redis.delete(_key)
        CommonMixin.delete_redis_keys(self, _redis)
        return
    
class AppInfo(CommonMixin, BaseModel):
    __tablename__ = "app_infos"
    
    app_key = Column("app_key", String(64))
    app_secret = Column("app_secret", String(64))
    
    app_name = Column("app_name", String(64))
    company_name = Column("company_name", String(64))
    
    app_icon = Column("app_icon", String(512))

    app_route_policy = Column("app_route_policy", String(64))
            
    welcome_message = Column("welcome_message", String(512))
    ppcom_launcher_color = Column("ppcom_launcher_color", String(16))

    
    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(AppInfo, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)

        _key = self.__tablename__
        _redis.set(_key, self.uuid)
        
        _key = self.__tablename__ + ".app_key." + self.app_key
        _redis.set(_key, self.uuid)

        return
    
    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, AppInfo, self.uuid)
        if _obj == None:
            return

        _key = self.__tablename__
        _redis.delete(_key)
        
        _key = self.__tablename__ + ".app_key." + _obj["app_key"]
        _redis.delete(_key)

        CommonMixin.delete_redis_keys(self, _redis)
        return


class ConversationInfo(CommonMixin, BaseModel):
    __tablename__ = "conversation_infos"

    user_uuid = Column("user_uuid", String(64))
    latest_task = Column("latest_task", String(64))
        
    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(ConversationInfo, self).__init__(*args, **kwargs)
        return
        
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)   
        return
    
    def delete_redis_keys(self, _redis):
        CommonMixin.delete_redis_keys(self, _redis)
        return

    def update_redis_keys(self, _redis):
        CommonMixin.update_redis_keys(self, _redis)
        return
    

class ConversationUserData(CommonMixin, BaseModel):
    __tablename__ = "conversation_user_datas"

    user_uuid = Column("user_uuid", String(64))
        
    # which is the peer user in the conversation since in conversation could be many users
    peer_uuid = Column("peer_uuid", String(64))

    # the user can define the conversation name and user name only show to himself
    conversation_name = Column("conversation_name", String(64))
    conversation_icon = Column("conversation_icon", String(512))
    conversation_uuid = Column("conversation_uuid", String(64))

    # S2P and S2S for service user, P2S is for customer user
    conversation_type = Column("conversation_type", String(8))
    
    # NEW/OPEN/CLOSE
    conversation_status = Column("conversation_status", String(16))

    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(ConversationUserData, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        
        _key = self.__tablename__ + \
               ".user_uuid." + self.user_uuid + \
               ".conversation_uuid." + self.conversation_uuid
        _redis.set(_key, self.uuid)
        
        _key = self.__tablename__ + \
               ".user_uuid." + self.user_uuid
        _redis.sadd(_key, self.conversation_uuid)

        _key = self.__tablename__ + \
               ".user_uuid." + self.user_uuid + \
               ".conversation_status." + self.conversation_status
        _updatetime = time.mktime(self.updatetime.timetuple())*1000*1000 + self.updatetime.microsecond
        _redis.zadd(_key, self.conversation_uuid, _updatetime)

        _key = self.__tablename__ + ".conversation_status." + self.conversation_status
        _updatetime = time.mktime(self.updatetime.timetuple())*1000*1000 + self.updatetime.microsecond
        _redis.zadd(_key, self.conversation_uuid, _updatetime)
        
        _key = self.__tablename__ + ".conversation_uuid." + self.conversation_uuid
        _redis.sadd(_key, self.user_uuid)

        _key = self.__tablename__ + ".conversation_uuid." + self.conversation_uuid + ".datas"
        _redis.sadd(_key, self.uuid)

        if self.peer_uuid:
            _key = self.__tablename__ + ".user_uuid." + self.user_uuid + ".peer_uuid." + self.peer_uuid
            _redis.set(_key, self.uuid)

        return

    def update_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.update_redis_keys(self, _redis, *args, **kwargs)
        _obj = redis_hash_to_dict(_redis, ConversationUserData, self.uuid)
        if _obj == None:
            return

        # REMOVE IT then ADD IT
        _statuses=[CONVERSATION_STATUS.NEW, CONVERSATION_STATUS.OPEN, CONVERSATION_STATUS.CLOSE]
        for _status in _statuses:
            _key = self.__tablename__ + \
                   ".user_uuid." + _obj["user_uuid"] + \
                   ".conversation_status." + _status
            _redis.zrem(_key, _obj["conversation_uuid"])

            _key = self.__tablename__ + ".conversation_status." + _status
            _redis.zrem(_key, _obj["conversation_uuid"])

        # user's conversations
        _key = self.__tablename__ + \
               ".user_uuid." + _obj["user_uuid"] + \
               ".conversation_status." + _obj["conversation_status"]
        _redis.zadd(_key, _obj["conversation_uuid"], time.time()*1000*1000)

        # app's conversations
        _key = self.__tablename__ + \
               ".conversation_status." + _obj["conversation_status"]
        _redis.zadd(_key, _obj["conversation_uuid"], time.time()*1000*1000)

        return

    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, ConversationUserData, self.uuid)
        if _obj == None:
            return
        _key = self.__tablename__ + \
               + ".user_uuid." + _obj["user_uuid"] + \
               ".conversation_uuid." + _obj["conversation_uuid"]
        _redis.delete(_key)
        
        _key = self.__tablename__ + \
               ".user_uuid." + _obj["user_uuid"]
        _redis.srem(_key, _obj["conversation_uuid"])

        _key = self.__tablename__ + \
               ".user_uuid." + _obj["user_uuid"] + \
               ".conversation_status." + _obj["conversation_status"]
        _redis.zrem(_key, _obj["conversation_uuid"])

        _key = self.__tablename__ + ".conversation_uuid." + _obj["conversation_uuid"]
        _redis.srem(_key, _obj["user_uuid"])

        _key = self.__tablename__ + ".conversation_uuid." + _obj["conversation_uuid"] + ".datas"
        _redis.srem(_key, self.uuid)


        if _obj.get("peer_uuid") and _obj.get("user_uuid"):
            _key = self.__tablename__ + ".user_uuid." + _obj.get("user_uuid") + ".peer_uuid." + _obj.get("peer_uuid")
            _redis.delete(_key)

        CommonMixin.delete_redis_keys(self, _redis)
        return

# PCSOCKET CLUSTER
class PCSocketInfo(CommonMixin, BaseModel):
    __tablename__ = "pc_socket_infos"

    host = Column("host", String(64))
    port = Column("port", String(16))
    latest_register_time = Column("latest_register_time", DateTime)
    
    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(PCSocketInfo, self).__init__(*args, **kwargs)
        return

    def create_redis_keys(self, _redis, *args, **kwargs):
        _key = self.__tablename__ \
               + ".host." + self.host \
               + ".port." + self.port
        _redis.set(_key, self.uuid)
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        return

    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, PCSocketInfo, self.uuid)
        if _obj == None:
            return
        _key = self.__tablename__ \
               + ".host." + _obj["host"] \
               + ".port." + _obj["port"]
        _redis.delete(_key)
        CommonMixin.delete_redis_keys(self, _redis)
        return


class PCSocketDeviceData(CommonMixin, BaseModel):
    __tablename__ = "pc_socket_device_datas"

    pc_socket_uuid = Column("pc_socket_uuid", String(64))
    device_uuid = Column("device_uuid", String(64))
    
    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(PCSocketDeviceData, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        _key = self.__tablename__ \
               + ".pc_socket_uuid." + self.pc_socket_uuid \
               + ".device_uuid." + self.device_uuid
        _redis.set(_key, self.uuid)

        _key = self.__tablename__ \
               + ".device_uuid." + self.device_uuid
        _redis.set(_key, self.pc_socket_uuid)

        _key = self.__tablename__ \
               + ".pc_socket_uuid." + self.pc_socket_uuid
        _redis.sadd(_key, self.device_uuid)
        
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        return

    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, PCSocketDeviceData, self.uuid)
        if _obj == None or _obj["pc_socket_uuid"] == None or _obj["device_uuid"] == None:
            return

        _key = self.__tablename__ \
               + ".pc_socket_uuid." + _obj["pc_socket_uuid"] \
               + ".device_uuid." + _obj["device_uuid"]
        _redis.delete(_key)

        _key = self.__tablename__ \
               + ".device_uuid." + _obj["device_uuid"]
        _redis.delete(_key)

        _key = self.__tablename__ \
               + ".pc_socket_uuid." + _obj["pc_socket_uuid"]
        _redis.srem(_key, _obj["device_uuid"])
        
        CommonMixin.delete_redis_keys(self, _redis)
        return

class UserNavigationData(CommonMixin, BaseModel):
    __tablename__ = "user_navigation_datas"

    user_uuid = Column("user_uuid", String(64))
    visit_page_url = Column("visit_page_url", String(1024))
    navigation_data = Column("navigation_data", String(2048))
    
    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(UserNavigationData, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)

        _key = self.__tablename__  + ".user_uuid." + self.user_uuid
        _createtime = time.mktime(self.createtime.timetuple())*1000*1000 + self.createtime.microsecond
        _v = json.dumps([_createtime, self.navigation_data])
        _redis.zadd(_key, _v, _createtime)

        if self.visit_page_url != None:
            _key = self.__tablename__  + ".user_uuid." + self.user_uuid + ".visit_page_url"
            _redis.set(_key, visit_page_url)
        return

    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, UserNavigationData, self.uuid)
        if _obj == None:
            return

        _key = self.__tablename__  + ".user_uuid." + _obj["user_uuid"]
        _createtime = time.mktime(_obj["createtime"].timetuple())*1000*1000 + _obj["createtime"].microsecond
        _v = json.dumps([_createtime, _obj["navigation_data"]])
        _redis.zrem(_key, _v)
        
        CommonMixin.delete_redis_keys(self, _redis)
        return

class ApiInfo(CommonMixin, BaseModel):
    __tablename__ = "api_infos"

    api_key = Column("api_key", String(64))
    api_secret = Column("api_secret", String(64))

    user_uuid = Column("user_uuid", String(64))

    # PPCOM/PPKEFU/PPCONSOLE/THIRD_PARTY_KEFU/THIRD_PARTY_CONSOLE
    api_level = Column("api_level", String(32))
    
    def __init__(self, *args, **kwargs):
        super(ApiInfo, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        _v = json.dumps([self.uuid, self.api_level, self.api_key, self.api_secret])
        
        _key = self.__tablename__ + ".api_key." + self.api_key
        _redis.set(_key, _v)

        _key = self.__tablename__ + \
               ".user_uuid." + self.user_uuid + \
               ".api_level." + self.api_level
        _redis.set(_key, _v)
        
        return
    
    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, ApiInfo, self.uuid)
        if _obj == None:
            return
        _key = self.__tablename__ + ".api_key." + _obj["api_key"]
        _redis.delete(_key)

        _key = self.__tablename__ + \
               ".user_uuid." + _obj["user_uuid"] + \
               ".api_level." + _obj["api_level"]
        _redis.delete(_key)
        
        CommonMixin.delete_redis_keys(self, _redis)
        return


class ApiTokenData(CommonMixin, BaseModel):
    __tablename__ = "api_token_datas"

    api_uuid = Column("api_uuid", String(64))
    api_level = Column("api_level", String(32))

    api_code = Column("api_code", String(256))
    api_token = Column("api_token", String(256))
    is_code_authorized = Column("is_code_authorized", Boolean)
    
    def __init__(self, *args, **kwargs):
        super(ApiTokenData, self).__init__(*args, **kwargs)
        return
    
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)

        _key = self.__tablename__ + ".api_token." + self.api_token
        _redis.set(_key, self.uuid)
        _redis.expire(_key, 30*60*60*24)
                
        # 30 seconds expired, if no token request in time, the code expired.
        _key = self.__tablename__ + ".api_code." + self.api_code
        _redis.set(_key, self.uuid)
        _redis.expire(_key, 30)
        return
    
    def delete_redis_keys(self, _redis):
        _obj = redis_hash_to_dict(_redis, ApiTokenData, self.uuid)
        if _obj == None:
            return
        _key = self.__tablename__ + ".api_token." + _obj["api_token"]
        _redis.delete(_key)
        _key = self.__tablename__ + ".api_code." + _obj["api_code"]
        _redis.delete(_key)
        
        CommonMixin.delete_redis_keys(self, _redis)
        return


class CompanyInfo(CommonMixin, BaseModel):
    __tablename__ = "company_infos"

    ent_company_uuid = Column("ent_company_uuid", String(64))
    ent_company_createtime = Column("ent_company_createtime", DateTime)
    
    company_name = Column("company_name", String(64))
    company_fullname = Column("company_fullname", String(256))

    company_icon = Column("company_icon", String(512))
    company_address = Column("company_address", String(256))
    company_phone = Column("company_phone", String(32))
    company_email = Column("company_email", String(64))


    extra_field_datas = Column("extra_field_datas", String(4096))
    
    __table_args__ = (
    )

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        return
        
    def create_redis_keys(self, _redis, *args, **kwargs):
        CommonMixin.create_redis_keys(self, _redis, *args, **kwargs)
        _key = self.__tablename__
        _redis.sadd(_key, self.uuid)

        _key = self.__tablename__ + ".ent_company_uuid." + self.ent_company_uuid
        _redis.set(_key, self.uuid)
        return

    def delete_redis_keys(self, _redis):
        CommonMixin.delete_redis_keys(self, _redis)
        return    

    def update_redis_keys(self, _redis):            
        CommonMixin.update_redis_keys(self, _redis)
        return
